name: Healthy Studio CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ 'master', 'dev' ]
  pull_request:
    branches: [ 'master', 'dev' ]

env:
  HEALTHY_STUDIO_API_IMAGE: ${{ vars.DOCKER_PREFIX }}:healthy-studio-api
  JWT_SECRET: ${{ secrets.JWT_SECRET }}

  # Common
  BRANCH_DEV: ${{ vars.BRANCH_DEV }}
  GITHUB_REF: ${{ github.ref }}

  SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
  SSH_USERNAME: ${{ secrets.SSH_USERNAME }}

  DOCKER_PREFIX: ${{ vars.DOCKER_PREFIX }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_NETWORK: ${{ vars.DOCKER_NETWORK }}
  DOCKER_NETWORK_GATEWAY: ${{ vars.DOCKER_NETWORK_GATEWAY }}
  DOCKER_NETWORK_IP_RANGE: ${{ vars.DOCKER_NETWORK_IP_RANGE }}
  DOCKER_NETWORK_SUBNET: ${{ vars.DOCKER_NETWORK_SUBNET }}

  HEALTHY_STUDIO_API_HOST_HTTP: ${{ secrets.HEALTHY_STUDIO_API_HOST_HTTP }}
  HEALTHY_STUDIO_API_IP: ${{ vars.HEALTHY_STUDIO_API_IP }}
  HEALTHY_STUDIO_API_PORT: ${{ vars.HEALTHY_STUDIO_API_PORT }}
  DATABASE_IP: ${{ vars.DATABASE_IP }}
  DATABASE_PORT: ${{ vars.DATABASE_PORT }}
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_PORT: ${{ secrets.SSH_PORT }}

  CONNECTION_CHECK_INTERVAL_MS: ${{ vars.CONNECTION_CHECK_INTERVAL_MS }}
  SPECS_DATA_AMOUNT: ${{ vars.SPECS_DATA_AMOUNT }}
  SPECS_HOOK_TIMEOUT_MS: ${{ vars.SPECS_HOOK_TIMEOUT_MS }}

jobs:
  check:
    name: Check files
    outputs:
      delta: ${{ steps.check.outputs.delta }}
    runs-on: ubuntu-latest
    env:
      EVENT_NAME: ${{ github.event_name }}
      EVENT_BEFORE: ${{ github.event.before }}
      EVENT_AFTER: ${{ github.event.after }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}

      - name: Check modified Healthy Studio API source files
        id: check
        shell: bash
        run: bash scripts/check-files.sh healthy-studio-api

  ci:
    name: Healthy Studio API CI
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.delta == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Docker network
        run: |
          echo $DOCKER_NETWORK_SUBNET
          echo $DOCKER_NETWORK_GATEWAY
          echo $DOCKER_NETWORK_IP_RANGE

          docker network create \
            --driver bridge \
            --subnet "$DOCKER_NETWORK_SUBNET" \
            --gateway "$DOCKER_NETWORK_GATEWAY" \
            --ip-range "$DOCKER_NETWORK_IP_RANGE" \
            $DOCKER_NETWORK

      - name: Login to DockerHub registry
        run: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin

      - name: Compose Healthy Studio API test
        run: docker compose --verbose --file docker/docker-compose.test.yml --profile healthy-studio-api up --build --abort-on-container-exit

  cd:
    name: Healthy Studio API CD
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: ci
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build production Healthy Studio API image
        run: |
          docker build \
            --file docker/configs/healthy-studio-api/Dockerfile.prod \
            --tag "${HEALTHY_STUDIO_API_IMAGE}-prod" \
            --build-arg HEALTHY_STUDIO_API_PORT=$HEALTHY_STUDIO_API_PORT \
            .

      - name: Login to DockerHub registry
        run: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin

      - name: Push production Healthy Studio API image
        run: docker push "${HEALTHY_STUDIO_API_IMAGE}-prod"

      - name: Pull and run Healthy Studio API image on remote host
        uses: appleboy/ssh-action@v1.0.0
        env:
          HEALTHY_STUDIO_API_IMAGE: ${{ vars.DOCKER_PREFIX }}:healthy-studio-api
          HEALTHY_STUDIO_API_CONTAINER: healthy-studio-api

          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKER_NETWORK: ${{ vars.DOCKER_NETWORK }}

          HEALTHY_STUDIO_API_IP: ${{ vars.HEALTHY_STUDIO_API_IP }}
          HEALTHY_STUDIO_API_PORT: ${{ vars.HEALTHY_STUDIO_API_PORT }}
        with:
          host: $SSH_HOST
          port: $SSH_PORT
          username: $SSH_USERNAME
          password: $SSH_PASSWORD
          envs:
            HEALTHY_STUDIO_API_IMAGE,
            HEALTHY_STUDIO_API_CONTAINER,

            DOCKERHUB_USERNAME,
            DOCKERHUB_PASSWORD,
            DOCKER_NETWORK,

            HEALTHY_STUDIO_API_IP,
            HEALTHY_STUDIO_API_PORT,

            NODE_ENV,
            HEALTHY_STUDIO_API_IMAGE_PROD,
            OLD_IMAGE
          script: |
            set -e
            export HEALTHY_STUDIO_API_IMAGE=$HEALTHY_STUDIO_API_IMAGE
            export HEALTHY_STUDIO_API_CONTAINER=$HEALTHY_STUDIO_API_CONTAINER

            export DOCKER_NETWORK=$DOCKER_NETWORK
            export DOCKERHUB_USERNAME=$DOCKERHUB_USERNAME
            export DOCKERHUB_PASSWORD=$DOCKERHUB_PASSWORD

            export HEALTHY_STUDIO_API_IP=$HEALTHY_STUDIO_API_IP
            export HEALTHY_STUDIO_API_PORT=$HEALTHY_STUDIO_API_PORT

            export NODE_ENV=prod
            export HEALTHY_STUDIO_API_IMAGE_PROD="${HEALTHY_STUDIO_API_IMAGE}-prod"

            export OLD_IMAGE=$(docker images -q $HEALTHY_STUDIO_API_IMAGE_PROD)$(echo "fallback")

            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker pull $HEALTHY_STUDIO_API_IMAGE_PROD

            docker stop $HEALTHY_STUDIO_API_CONTAINER || true
            docker container rm -f $HEALTHY_STUDIO_API_CONTAINER
            docker image rm -f $OLD_IMAGE

            command="docker run -dit \
              --restart unless-stopped \
              --publish $HEALTHY_STUDIO_API_PORT:$HEALTHY_STUDIO_API_PORT \
              --name $HEALTHY_STUDIO_API_CONTAINER \
              --net $DOCKER_NETWORK \
              --ip $HEALTHY_STUDIO_API_IP \
              --env $HEALTHY_STUDIO_API_PORT \
              --env $NODE_ENV \
              $HEALTHY_STUDIO_API_IMAGE_PROD"
            echo $command
            eval $command
            docker ps
